homeassistant:
  name: HHZ
  latitude: 48.679763
  longitude: 8.999435
  elevation: 410
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customized.yaml


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

light:
  platform: hue

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml

mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
      baud_rate: 115200
  optimistic: false
  persistence: true
  retain: true
  version: 2.0

