- platform: darksky
  api_key: 2b0a14341b4c67db191f708c7d6dea4e
  name: weather
  monitored_conditions:
    - temperature
    - apparent_temperature
    - wind_speed
    - cloud_cover
    - humidity
    - pressure

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
    - type: since_last_boot
    
- platform: time_date
  display_options:
    - 'time'
      
- platform: statistics
  name: breakrequeststatistics
  friendly_name: Break requests statistics
  entity_id: input_boolean.breakrequest

- platform: template
  sensors:
    stopwatch:
      friendly_name: "Timer"
      value_template: >
        {% if is_state('input_boolean.stopwatch', 'on') %}
          {{ ((now() - states.automation.stopwatch_start.attributes.last_triggered).total_seconds()/60) | round | int }}
        {% elif is_state('sensor.stopwatch', 'unknown') %}
          0
        {% else %}
          {{ states('sensor.stopwatch') }}
        {% endif %}
      icon_template: mdi:clock
      unit_of_measurement: 'min'
      entity_id:
        - automation.stopwatch_start
        - automation.stopwatch_update
        - automation.stopwatch_stop
    breakscore:
      friendly_name: "Break score"
      value_template: >
        {% if is_state('input_boolean.stopwatch', 'on') %}
          {{ (((now() - states.automation.stopwatch_start.attributes.last_triggered).total_seconds()/60) + (5 * states.sensor.breakrequeststatistics_mean.attributes.count)) | round | int }}
          {% elif is_state('sensor.stopwatch', 'unknown') %}
            0
          {% else %}
            {{ states('sensor.stopwatch') }}
          {% endif %}
      icon_template: mdi:gauge
      entity_id:
        - automation.stopwatch_start
        - automation.stopwatch_update
        - automation.stopwatch_stop
    breakrequestcount:
      friendly_name: Break request count
      value_template: > 
        {% if is_state('input_boolean.stopwatch', 'on') %}
          {{ states.sensor.breakrequeststatistics_mean.attributes.count }}
        {% elif is_state('sensor.stopwatch', 'unknown') %}
          0
        {% else %}
          {{ states('sensor.stopwatch') }}
        {% endif %}
         